# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tsfdb_server_v1.models.base_model_ import Model
from tsfdb_server_v1 import util


class Resource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, metrics=None):  # noqa: E501
        """Resource - a model defined in OpenAPI

        :param id: The id of this Resource.  # noqa: E501
        :type id: str
        :param metrics: The metrics of this Resource.  # noqa: E501
        :type metrics: List[str]
        """
        self.openapi_types = {
            'id': str,
            'metrics': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'metrics': 'metrics'
        }

        self._id = id
        self._metrics = metrics

    @classmethod
    def from_dict(cls, dikt) -> 'Resource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Resource of this Resource.  # noqa: E501
        :rtype: Resource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Resource.


        :return: The id of this Resource.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Resource.


        :param id: The id of this Resource.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def metrics(self):
        """Gets the metrics of this Resource.


        :return: The metrics of this Resource.
        :rtype: List[str]
        """
        return self._metrics

    @metrics.setter
    def metrics(self, metrics):
        """Sets the metrics of this Resource.


        :param metrics: The metrics of this Resource.
        :type metrics: List[str]
        """
        if metrics is None:
            raise ValueError("Invalid value for `metrics`, must not be `None`")  # noqa: E501

        self._metrics = metrics
