# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from tsfdb_server_v1.models.base_model_ import Model
from tsfdb_server_v1 import util


class SeriesResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datapoints=None):  # noqa: E501
        """SeriesResponse - a model defined in OpenAPI

        :param datapoints: The datapoints of this SeriesResponse.  # noqa: E501
        :type datapoints: List[List[float]]
        """
        self.openapi_types = {
            'datapoints': List[List[float]]
        }

        self.attribute_map = {
            'datapoints': 'datapoints'
        }

        self._datapoints = datapoints

    @classmethod
    def from_dict(cls, dikt) -> 'SeriesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SeriesResponse of this SeriesResponse.  # noqa: E501
        :rtype: SeriesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datapoints(self):
        """Gets the datapoints of this SeriesResponse.


        :return: The datapoints of this SeriesResponse.
        :rtype: List[List[float]]
        """
        return self._datapoints

    @datapoints.setter
    def datapoints(self, datapoints):
        """Sets the datapoints of this SeriesResponse.


        :param datapoints: The datapoints of this SeriesResponse.
        :type datapoints: List[List[float]]
        """

        self._datapoints = datapoints
